import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import Sidebar from '../components/Sidebar';
import { useAuth } from '../Context/Authcontext';

export default function Home() {
  const route = useRouter();
  const { currentUser } = useAuth();

  if (!currentUser) { route.push('/login'); return null; }

  return (
    <>
      <Head>
        <title>Whatsapp Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Sidebar />
      </div>
    </>
  );
}
